window.project1Content = {
  eyebrow: "Project 1",
  title: "Images of the<br>Russian Empire",
  subtitle: "Colorizing the Prokudin-Gorskii Photo Collection",

  generalApproachHeading: "General Approach →",
  generalApproachIntro: `Prokudin-Gorskii photographed each scene three times through blue, green, and red filters. The digitized glass plate places these monochrome exposures one above another in blue, green, and red order. I divide the plate height by three to recover one image for each color channel. The height is not always exactly divisible by three, so I ignore any leftover rows at the bottom and keep all three channels the same size.`,
  comparingIntro: `The recovered channels cannot simply be stacked. The camera, the glass plate, and sometimes the subjects moved slightly between exposures, so a point in the scene may appear at a different coordinate in each channel. To correct this misalignment, I keep blue fixed and search for one translation for green and another for red. I then apply the two translations and stack the aligned channels to form the color image.`,
  nccIntro: `The search needs a way to decide whether two channels are aligned. I use normalized cross-correlation (NCC), which subtracts the mean intensity from each image and divides their dot product by the product of their magnitudes. This normalization reduces the effect of an overall brightness difference between channels. A high NCC score means that their bright and dark patterns occur in similar places, even when one channel is brighter than the other.`,
  nccFormula: `\\[\\operatorname{NCC}(A,B)=\\frac{(A-\\bar{A})\\cdot(B-\\bar{B})}{\\lVert A-\\bar{A}\\rVert_2\\,\\lVert B-\\bar{B}\\rVert_2}\\]`,
  borderExplanation: `For each candidate translation, I shift the moving channel with <code>np.roll</code>. This operation wraps pixels that leave one edge around to the opposite edge, where they no longer represent valid overlap. The scans also contain bright and dark plate borders whose widths differ between channels. Either feature could distort the score, so I compute NCC only on the central 80% of the shifted images. This crop is used only for comparison. The final saved image still contains the full channels.`,
  offsetConvention: `After scoring every candidate, I select the shift with the highest NCC. Every offset below is written as (x, y). A positive x value moves the channel to the right, and a positive y value moves it downward. I use the same crop and search settings for every image rather than tuning the method one image at a time.`,

  singleScaleHeading: "Single-Scale →",
  singleScaleExplanation: `The three JPEGs are small enough for a direct exhaustive search. I begin with green and test every integer displacement from −15 to +15 pixels in both x and y. At each of the 961 positions, I shift the channel, compare its interior with the blue interior, and record the NCC score. I then repeat the same search independently for red. After choosing the best displacement for each channel, I apply both shifts and stack the result. Each JPEG finishes in well under a second, and the aligned edges show that a translation is enough for these three images.`,

  pyramidHeading: "Image Pyramid →",
  pyramidIntro: `The same exhaustive search does not scale well to the TIFF scans. These images are several thousand pixels tall, and their correct offsets can be much larger than 15 pixels. Searching a wide range at full resolution would require many comparisons between large arrays. Instead, I use an image pyramid to estimate most of the displacement on smaller images, where each comparison is much cheaper.`,
  coarseToFineExplanation: `I build the pyramid recursively by resizing both the moving channel and the blue reference to half their width and height. This continues until the largest dimension is at most 400 pixels. I then run the full search from −15 to +15 pixels at this coarsest level. A single pixel here represents several pixels in the original image, so the search covers a large full-resolution displacement without requiring a large window.`,
  pyramidOutputExplanation: `The coarse result becomes the starting point for the next finer level. Since the image dimensions double, I also multiply both coordinates of the estimated offset by two. I search only within ±2 pixels of that prediction, which corrects small errors introduced by resizing and rounding. The estimate is doubled and refined again at every level until the algorithm returns to full resolution. These resized images are used only to estimate the displacement. I apply the final offset once to the original channel, so repeated resizing does not soften the saved image. Each caption lists the final green and red offsets and the total runtime. Clicking a large image below reveals the offset chosen at every level from coarsest to finest.`,

  selectedHeading: "Selected Plates →",
  selectedExplanation: `To test the method beyond the supplied images, I chose three additional high-resolution plates from the Library of Congress. The roof of Milan Cathedral provides many sharp architectural edges. Capri combines a textured rock face, hillside vegetation, and layered buildings. Lugano contains fine detail along the shoreline and across the hillside. I processed all three with the same NCC pyramid settings used for the supplied TIFF files. Their channels aligned cleanly without any image-specific changes.`,

  failureHeading: "Failure & Correction →",
  failureExplanation: `The Emir of Bukhara is the main failure of direct red-to-blue alignment. A filtered exposure measures how much light the scene reflects within that filter’s range of wavelengths. The saturated blue robe reflects blue light strongly but absorbs much of the red light, so it is bright and detailed in the blue exposure but much darker in red. NCC can compensate for a global change in mean and scale, but it cannot undo this spatially varying change in contrast. Because the robe fills much of the scoring crop, its mismatch leads NCC to the incorrect red offset of (−205, 141).`,
  failureConclusion: `The green exposure retains enough structure from both sides of the spectrum to match blue reliably and to resemble red more closely than blue does. I therefore align red to the original green channel at (17, 57), then add green’s offset to blue at (24, 49). The composed red-to-blue offset is (41, 106). Green does not modify red. It acts as an intermediate reference that connects a more reliable red-to-green match back to blue coordinates.`
};
